### PR TITLE
Sensible merging with upstream

### PR DESCRIPTION
**Pull request by neoflex**
I finally took the time to try to resolve the merging issues to keep spotyXBMC2 up to date with master.
It seems to be working but I think it should be tested by others before integrating. There has been some changes on CSong, CAlbum, and others classes which had some consequences for spotify files.

### CODE REVIEW

**Comment by akezeke** [comment]
Great work! Compiling now!

**Comment by akezeke** [comment]
Works well on my system! Thanks for the merge, have you looked at newest version of libspotify?

**Comment by neoflex** [comment]
Great to hear that it works.
No, didn't look the libspotify update. I'll let you this :p

**Comment by akezeke** [comment]
Hi,

I guess we should stick with the version we use now then!

2012/5/11 Valentin Grouès <
reply@reply.github.com

**Comment by neoflex** [comment]
Yep, until they block old versions ;)
If you have a little bit of time, I am kind of stuck with the next merge with upstream.
They merged the AudioEngine branch and even if it still compiles with spotify, it crashes as soon as I try to play a spotify song.

**Pull request merged**
