### PR TITLE
dynamically link library at runtime

### PR DESCRIPTION
**Pull request by escoand**
first try, and working

### CODE REVIEW

**Comment by escoand** [comment]
what should be done to not get a copy of api.h and licensing problems?

**Comment by tompen-** [comment]
If you would squash these commits into one commit, then force push your branch to github again it would be easier for akezeke to review.

**Comment by escoand** [comment]
@tompen- Done.

I searched a bit in the web: I think we have to rename the structs, enums, functions, ... to not ge a copyright problem...

**Comment by escoand** [comment]
Are there some new informations concerning this topic?

**Pull request closed without merging**
