### PR TITLE
updated spotyxbmc2 with latest xbmc frodo rc1

### PR DESCRIPTION
**Pull request by NuroPreak**

### CODE REVIEW

**Comment by neoflex** [comment]
thanks for the PR. What is this file exactly? : https://github.com/NuroPreak/xbmc/blob/master/lib/asap/win32/1

**Comment by NuroPreak** [comment]
i did not deleted "g_spotify = new Addon_music_spotify();" it is in application.cpp.

As for the other thing, i don't have a clue how it got there looks like it got there by accident.

**Comment by NuroPreak** [comment]
note i'm not an expert :)

**Comment by neoflex** [comment]
thanks, merging done

**Pull request closed without merging**
